/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";
import Image from "next/image";

function HeaderComponent() {
  return (
    <Header>
      <CustomImage src="/B64-white.png" alt="" loading="lazy" 
      width={120}
      height={100}
      />
      <Navigation>
        <Link>Home</Link>
        <Link>Contact</Link>
      </Navigation>
    </Header>
  );
}

const Header = styled.header`
  align-items: center;
  display: flex;
  justify-content: space-between;
  padding: 16px;
  background-color: rgba(36, 36, 36, 1);
`;

const CustomImage = styled(Image)`
  aspect-ratio: 1;
  object-fit: cover;
  object-position: center;
  width: 120px;
`;

const Navigation = styled.nav`
  align-items: center;
  display: flex;
  font-size: 30px;
`;

const Link = styled.a`
  text-decoration: none;
  margin-right: 24px;
  @media (max-width: 640px) {
    font-size: 24px;
  }
`;

export default HeaderComponent;